### ISSUE TITLE
Lab hours display incorrectly if name is substring of another name

### ISSUE THREAD

**Issue by chulse** [bryanjwong/sparkieee#3]
https://github.com/bryanjwong/sparkieee/blob/951ab74c6ad04a4f32410460a87ff5341169d5bb/sheet_transformer.py#L277

IE: Kat's lab hours include Kathy's
![image](https://user-images.githubusercontent.com/39817852/115602452-cc839600-a293-11eb-9466-a21a7d31871a.png)

**Comment by bryanjwong** [comment]
Known bug (See comment at https://github.com/bryanjwong/sparkieee/blob/master/bot.py#L218) 

Can look into solution later. Probably involves searching for name from spreadsheet (maybe first occurrence?) and only returning exact matches of that name.
